### ISSUE TITLE
Place Holder Images

### ISSUE THREAD

**Issue by dustinmazon** [wvuweb/wvu-brand-patterns-theme#23]
We might consider using http://placehold.it/ to create images instead of adding unnecessary assets to the patterns. That would help prevent people from uploading extra files/bulk to our themes repo. Thoughts on this?

**Comment by zeroedin** [comment]
Assuming your are talking about when it comes to using background images or radius image tags like the thumbnails or media block in bootstrap?

http://getbootstrap.com/components/#thumbnails 
http://getbootstrap.com/components/#media  

Instead of using css base64 encoded backgrounds or using a standard image tag by linking to the placehold.it images?

**Comment by dustinmazon** [comment]
I am talking about using placehold.it to generate a place holder image for the hero, triptych, diptych and other images in our patterns to prevent us from having to download unnecessary files. 

Example: for the _wvu-landing-page-header.html pattern we could use placehold.it instead linking to ../images/dance-header.jpg

My main point is that we do not need to have default image files in the images folder... we should look at what needs to be an asset and what needs to be a place holder image.

**Comment by dustinmazon** [comment]
Y

**Comment by adamglenn** [comment]
Dustin, for this I am going to just use absolute links to actual WVU-branded placeholder images in an external theme. That way they won't have to download/upload any extra images.

**Comment by zeroedin** [comment]
Maybe put those in static instead of a "theme".
